name: CI

on:
  push:
    branches:
      - master
  pull_request: 

env:
  APP: ns-hello

jobs:
  build-image:
    uses: lneves75/gh-workflows/.github/workflows/ci.yaml@master
    with:
      app-name: ns-hello
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - run: npm install --ignore-scripts
      - run: npm run build

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - run: npm install --ignore-scripts
      - run: npm run test

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - run: npm install --ignore-scripts
      - run: npm run format
      - run: npm run lint